import type { Imovel } from '@/types/imovel';

export const IMOVEIS_MOCK: Imovel[] = [
  {
    id: 'imovel-001',
    titulo: 'Apartamento T2 renovado em Campo de Ourique',
    descricao:
      'Excelente apartamento T2 totalmente renovado, situado numa das zonas mais procuradas de Lisboa. Cozinha equipada, pavimento em madeira maciça, janelas com vidro duplo e isolamento térmico. Próximo de transportes, comércio e escolas. Exposição solar nascente/poente com muita luminosidade natural.',
    preco: 245000,
    tipologia: 'T2',
    area_util: 78,
    area_bruta: 92,
    quartos: 2,
    casas_banho: 1,
    andar: '3.º',
    estado: 'renovado',
    tipo: 'apartamento',
    finalidade: 'venda',
    distrito: 'Lisboa',
    concelho: 'Lisboa',
    freguesia: 'Campo de Ourique',
    morada: 'Rua Ferreira Borges 42',
    codigo_postal: '1350-128',
    latitude: 38.7167,
    longitude: -9.1636,
    garagem: false,
    elevador: true,
    varanda: true,
    terraço: false,
    jardim: false,
    piscina: false,
    ar_condicionado: true,
    certificado_energetico: 'B',
    fotos: [
      'https://picsum.photos/seed/imovel1a/800/600',
      'https://picsum.photos/seed/imovel1b/800/600',
      'https://picsum.photos/seed/imovel1c/800/600',
      'https://picsum.photos/seed/imovel1d/800/600',
    ],
    foto_principal: 'https://picsum.photos/seed/imovel1a/800/600',
    portal: 'idealista',
    url_original: 'https://www.idealista.pt/imovel/12345678/',
    referencia_portal: 'IDL-12345678',
    aceita_corretores: 'SIM',
    data_publicacao: '2026-07-01',
    data_scraping: '2026-07-15T10:30:00Z',
    data_atualizacao: '2026-07-15T10:30:00Z',
    ativo: true,
  },
  {
    id: 'imovel-002',
    titulo: 'Moradia T4 com jardim na Foz do Douro',
    descricao:
      'Magnífica moradia T4 na Foz do Douro, com jardim privativo e garagem para 2 carros. Sala ampla com lareira, cozinha equipada, 4 quartos (1 suite), 3 casas de banho. Terraço com vista rio. Zona residencial tranquila, próxima da praia e do Parque da Cidade.',
    preco: 385000,
    tipologia: 'T4',
    area_util: 195,
    area_bruta: 230,
    area_terreno: 350,
    quartos: 4,
    casas_banho: 3,
    andar: 'R/C + 1.º',
    estado: 'usado',
    tipo: 'moradia',
    finalidade: 'venda',
    distrito: 'Porto',
    concelho: 'Porto',
    freguesia: 'Foz do Douro',
    morada: 'Rua do Passeio Alegre 118',
    codigo_postal: '4150-572',
    latitude: 41.1496,
    longitude: -8.6710,
    garagem: true,
    elevador: false,
    varanda: true,
    terraço: true,
    jardim: true,
    piscina: false,
    ar_condicionado: true,
    certificado_energetico: 'C',
    fotos: [
      'https://picsum.photos/seed/imovel2a/800/600',
      'https://picsum.photos/seed/imovel2b/800/600',
      'https://picsum.photos/seed/imovel2c/800/600',
      'https://picsum.photos/seed/imovel2d/800/600',
      'https://picsum.photos/seed/imovel2e/800/600',
    ],
    foto_principal: 'https://picsum.photos/seed/imovel2a/800/600',
    portal: 'imovirtual',
    url_original: 'https://www.imovirtual.com/anuncio/87654321',
    referencia_portal: 'IMV-87654321',
    aceita_corretores: 'SIM',
    data_publicacao: '2026-06-20',
    data_scraping: '2026-07-14T09:00:00Z',
    data_atualizacao: '2026-07-14T09:00:00Z',
    ativo: true,
  },
  {
    id: 'imovel-003',
    titulo: 'Apartamento T1 para arrendamento na Baixa de Coimbra',
    descricao:
      'Apartamento T1 mobilado e equipado para arrendamento na Baixa de Coimbra. Ideal para estudantes ou jovens profissionais. Sala com kitchenette, quarto com roupeiro embutido, casa de banho completa. A 5 minutos a pé da Universidade de Coimbra.',
    preco: 650,
    tipologia: 'T1',
    area_util: 45,
    area_bruta: 52,
    quartos: 1,
    casas_banho: 1,
    andar: '2.º',
    estado: 'renovado',
    tipo: 'apartamento',
    finalidade: 'arrendamento',
    distrito: 'Coimbra',
    concelho: 'Coimbra',
    freguesia: 'Sé Nova',
    morada: 'Rua da Sofia 85',
    codigo_postal: '3000-389',
    latitude: 40.2088,
    longitude: -8.4268,
    garagem: false,
    elevador: false,
    varanda: false,
    terraço: false,
    jardim: false,
    piscina: false,
    ar_condicionado: false,
    certificado_energetico: 'D',
    fotos: [
      'https://picsum.photos/seed/imovel3a/800/600',
      'https://picsum.photos/seed/imovel3b/800/600',
      'https://picsum.photos/seed/imovel3c/800/600',
    ],
    foto_principal: 'https://picsum.photos/seed/imovel3a/800/600',
    portal: 'olx',
    url_original: 'https://www.olx.pt/anuncio/apart-t1-coimbra-11223344',
    referencia_portal: 'OLX-11223344',
    aceita_corretores: 'SIM',
    data_publicacao: '2026-07-10',
    data_scraping: '2026-07-16T14:00:00Z',
    data_atualizacao: '2026-07-16T14:00:00Z',
    ativo: true,
  },
  {
    id: 'imovel-004',
    titulo: 'Terreno urbano com vista mar em Albufeira',
    descricao:
      'Terreno urbano com 1.200 m² para construção de moradia unifamiliar, situado em zona privilegiada de Albufeira com vista mar. Projeto aprovado para moradia de 2 pisos. Todas as infraestruturas disponíveis (água, eletricidade, saneamento). A 10 minutos da Praia dos Pescadores.',
    preco: 120000,
    tipologia: 'T0',
    area_terreno: 1200,
    estado: 'novo',
    tipo: 'terreno',
    finalidade: 'venda',
    distrito: 'Faro',
    concelho: 'Albufeira',
    freguesia: 'Albufeira e Olhos de Água',
    morada: 'Estrada de Vale Pedras',
    codigo_postal: '8200-211',
    latitude: 37.0893,
    longitude: -8.2500,
    garagem: false,
    elevador: false,
    varanda: false,
    terraço: false,
    jardim: false,
    piscina: false,
    ar_condicionado: false,
    fotos: [
      'https://picsum.photos/seed/imovel4a/800/600',
      'https://picsum.photos/seed/imovel4b/800/600',
    ],
    foto_principal: 'https://picsum.photos/seed/imovel4a/800/600',
    portal: 'idealista',
    url_original: 'https://www.idealista.pt/imovel/55667788/',
    referencia_portal: 'IDL-55667788',
    aceita_corretores: 'SIM',
    data_publicacao: '2026-06-15',
    data_scraping: '2026-07-12T08:00:00Z',
    data_atualizacao: '2026-07-12T08:00:00Z',
    ativo: true,
  },
  {
    id: 'imovel-005',
    titulo: 'Apartamento T3 novo com garagem em Braga',
    descricao:
      'Apartamento T3 novo em condomínio fechado na zona de Nogueiró, Braga. Acabamentos de qualidade superior, cozinha equipada com eletrodomésticos Bosch, pavimento flutuante, estores elétricos. Garagem fechada para 1 carro e arrecadação. Próximo de escolas, supermercados e acessos à autoestrada.',
    preco: 195000,
    tipologia: 'T3',
    area_util: 110,
    area_bruta: 135,
    quartos: 3,
    casas_banho: 2,
    andar: '1.º',
    estado: 'novo',
    tipo: 'apartamento',
    finalidade: 'venda',
    distrito: 'Braga',
    concelho: 'Braga',
    freguesia: 'Nogueiró e Tenões',
    morada: 'Rua de Nogueiró 234',
    codigo_postal: '4715-310',
    latitude: 41.5633,
    longitude: -8.4217,
    garagem: true,
    elevador: true,
    varanda: true,
    terraço: false,
    jardim: false,
    piscina: false,
    ar_condicionado: true,
    certificado_energetico: 'A',
    fotos: [
      'https://picsum.photos/seed/imovel5a/800/600',
      'https://picsum.photos/seed/imovel5b/800/600',
      'https://picsum.photos/seed/imovel5c/800/600',
      'https://picsum.photos/seed/imovel5d/800/600',
    ],
    foto_principal: 'https://picsum.photos/seed/imovel5a/800/600',
    portal: 'imovirtual',
    url_original: 'https://www.imovirtual.com/anuncio/99887766',
    referencia_portal: 'IMV-99887766',
    aceita_corretores: 'SIM',
    data_publicacao: '2026-07-05',
    data_scraping: '2026-07-15T16:00:00Z',
    data_atualizacao: '2026-07-15T16:00:00Z',
    ativo: true,
  },
  {
    id: 'imovel-006',
    titulo: 'Moradia T3 com piscina em Palmela',
    descricao:
      'Moradia isolada T3 com piscina e jardim em Palmela, com vista para a Serra da Arrábida. 3 quartos (1 suite com closet), 2 casas de banho, sala com 40 m², cozinha americana. Piscina aquecida, churrasqueira, garagem para 2 carros. Painéis solares e bomba de calor.',
    preco: 320000,
    tipologia: 'T3',
    area_util: 160,
    area_bruta: 200,
    area_terreno: 500,
    quartos: 3,
    casas_banho: 2,
    andar: 'R/C + 1.º',
    estado: 'usado',
    tipo: 'moradia',
    finalidade: 'venda',
    distrito: 'Setubal',
    concelho: 'Palmela',
    freguesia: 'Palmela',
    morada: 'Travessa dos Olivais 15',
    codigo_postal: '2950-204',
    latitude: 38.5687,
    longitude: -8.9012,
    garagem: true,
    elevador: false,
    varanda: false,
    terraço: true,
    jardim: true,
    piscina: true,
    ar_condicionado: true,
    certificado_energetico: 'B-',
    fotos: [
      'https://picsum.photos/seed/imovel6a/800/600',
      'https://picsum.photos/seed/imovel6b/800/600',
      'https://picsum.photos/seed/imovel6c/800/600',
      'https://picsum.photos/seed/imovel6d/800/600',
      'https://picsum.photos/seed/imovel6e/800/600',
    ],
    foto_principal: 'https://picsum.photos/seed/imovel6a/800/600',
    portal: 'idealista',
    url_original: 'https://www.idealista.pt/imovel/33445566/',
    referencia_portal: 'IDL-33445566',
    aceita_corretores: 'SIM',
    data_publicacao: '2026-06-28',
    data_scraping: '2026-07-13T11:30:00Z',
    data_atualizacao: '2026-07-13T11:30:00Z',
    ativo: true,
  },
  {
    id: 'imovel-007',
    titulo: 'Apartamento T2 para arrendamento no Parque das Nacoes',
    descricao:
      'Apartamento T2 moderno para arrendamento no Parque das Nacoes, Lisboa. Vista rio, cozinha equipada, 2 quartos com roupeiro, 1 casa de banho completa. Condominio com piscina e ginasio. Garagem incluida. Proximo do Centro Vasco da Gama e estacao do Metro Oriente.',
    preco: 1200,
    tipologia: 'T2',
    area_util: 85,
    area_bruta: 100,
    quartos: 2,
    casas_banho: 1,
    andar: '8.º',
    estado: 'usado',
    tipo: 'apartamento',
    finalidade: 'arrendamento',
    distrito: 'Lisboa',
    concelho: 'Lisboa',
    freguesia: 'Parque das Nacoes',
    morada: 'Rua dos Argonautas 12',
    codigo_postal: '1990-005',
    latitude: 38.7630,
    longitude: -9.0940,
    garagem: true,
    elevador: true,
    varanda: true,
    terraço: false,
    jardim: false,
    piscina: true,
    ar_condicionado: true,
    certificado_energetico: 'B',
    fotos: [
      'https://picsum.photos/seed/imovel7a/800/600',
      'https://picsum.photos/seed/imovel7b/800/600',
      'https://picsum.photos/seed/imovel7c/800/600',
    ],
    foto_principal: 'https://picsum.photos/seed/imovel7a/800/600',
    portal: 'olx',
    url_original: 'https://www.olx.pt/anuncio/t2-parque-nacoes-44556677',
    referencia_portal: 'OLX-44556677',
    aceita_corretores: 'SIM',
    data_publicacao: '2026-07-08',
    data_scraping: '2026-07-16T09:45:00Z',
    data_atualizacao: '2026-07-16T09:45:00Z',
    ativo: true,
  },
  {
    id: 'imovel-008',
    titulo: 'Apartamento T1 remodelado na Ribeira, Porto',
    descricao:
      'Encantador apartamento T1 totalmente remodelado na zona historica da Ribeira, Porto. Paredes em pedra a vista, tetos com vigas de madeira, cozinha moderna. Quarto com vista para o rio Douro. Ideal para habitacao propria ou investimento em alojamento local.',
    preco: 145000,
    tipologia: 'T1',
    area_util: 42,
    area_bruta: 50,
    quartos: 1,
    casas_banho: 1,
    andar: '1.º',
    estado: 'renovado',
    tipo: 'apartamento',
    finalidade: 'venda',
    distrito: 'Porto',
    concelho: 'Porto',
    freguesia: 'Cedofeita, Santo Ildefonso, Se, Miragaia, Sao Nicolau e Vitoria',
    morada: 'Rua de Sao Joao 77',
    codigo_postal: '4050-551',
    latitude: 41.1408,
    longitude: -8.6130,
    garagem: false,
    elevador: false,
    varanda: false,
    terraço: false,
    jardim: false,
    piscina: false,
    ar_condicionado: false,
    certificado_energetico: 'C',
    fotos: [
      'https://picsum.photos/seed/imovel8a/800/600',
      'https://picsum.photos/seed/imovel8b/800/600',
      'https://picsum.photos/seed/imovel8c/800/600',
    ],
    foto_principal: 'https://picsum.photos/seed/imovel8a/800/600',
    portal: 'idealista',
    url_original: 'https://www.idealista.pt/imovel/77889900/',
    referencia_portal: 'IDL-77889900',
    aceita_corretores: 'SIM',
    data_publicacao: '2026-07-03',
    data_scraping: '2026-07-14T15:20:00Z',
    data_atualizacao: '2026-07-14T15:20:00Z',
    ativo: true,
  },
  {
    id: 'imovel-009',
    titulo: 'Moradia T5 de luxo em Cascais',
    descricao:
      'Moradia de luxo T5 em Cascais, com 5 quartos (3 suites), sala de estar com 60 m², escritorio, sala de cinema. Cozinha Siemens totalmente equipada. Jardim com piscina infinita e vista mar. Garagem para 3 carros. Domótica integral. Seguranca 24h.',
    preco: 450000,
    preco_anterior: 480000,
    tipologia: 'T5+',
    area_util: 320,
    area_bruta: 400,
    area_terreno: 800,
    quartos: 5,
    casas_banho: 4,
    andar: 'R/C + 1.º + Cave',
    estado: 'usado',
    tipo: 'moradia',
    finalidade: 'venda',
    distrito: 'Lisboa',
    concelho: 'Cascais',
    freguesia: 'Cascais e Estoril',
    morada: 'Avenida Marginal',
    codigo_postal: '2750-357',
    latitude: 38.6965,
    longitude: -9.4215,
    garagem: true,
    elevador: true,
    varanda: true,
    terraço: true,
    jardim: true,
    piscina: true,
    ar_condicionado: true,
    certificado_energetico: 'A+',
    fotos: [
      'https://picsum.photos/seed/imovel9a/800/600',
      'https://picsum.photos/seed/imovel9b/800/600',
      'https://picsum.photos/seed/imovel9c/800/600',
      'https://picsum.photos/seed/imovel9d/800/600',
      'https://picsum.photos/seed/imovel9e/800/600',
      'https://picsum.photos/seed/imovel9f/800/600',
    ],
    foto_principal: 'https://picsum.photos/seed/imovel9a/800/600',
    portal: 'imovirtual',
    url_original: 'https://www.imovirtual.com/anuncio/22334455',
    referencia_portal: 'IMV-22334455',
    aceita_corretores: 'NAO',
    restricao_texto: 'Venda direta do proprietario. Nao aceito contactos de imobiliarias ou intermediarios.',
    data_publicacao: '2026-06-10',
    data_scraping: '2026-07-11T07:00:00Z',
    data_atualizacao: '2026-07-11T07:00:00Z',
    ativo: true,
  },
  {
    id: 'imovel-010',
    titulo: 'Apartamento T2 com vista mar em Quarteira',
    descricao:
      'Apartamento T2 em primeira linha de mar em Quarteira, Algarve. Sala com varanda e vista mar panoramica, 2 quartos, 1 casa de banho, cozinha semi-equipada. Condominio com piscina exterior e jardim. Estacionamento privativo. Ideal para ferias ou investimento.',
    preco: 175000,
    tipologia: 'T2',
    area_util: 72,
    area_bruta: 85,
    quartos: 2,
    casas_banho: 1,
    andar: '4.º',
    estado: 'usado',
    tipo: 'apartamento',
    finalidade: 'venda',
    distrito: 'Faro',
    concelho: 'Loule',
    freguesia: 'Quarteira',
    morada: 'Avenida Infante de Sagres 200',
    codigo_postal: '8125-156',
    latitude: 37.0681,
    longitude: -8.1059,
    garagem: false,
    elevador: true,
    varanda: true,
    terraço: false,
    jardim: false,
    piscina: true,
    ar_condicionado: true,
    certificado_energetico: 'D',
    fotos: [
      'https://picsum.photos/seed/imovel10a/800/600',
      'https://picsum.photos/seed/imovel10b/800/600',
      'https://picsum.photos/seed/imovel10c/800/600',
      'https://picsum.photos/seed/imovel10d/800/600',
    ],
    foto_principal: 'https://picsum.photos/seed/imovel10a/800/600',
    portal: 'olx',
    url_original: 'https://www.olx.pt/anuncio/t2-quarteira-vista-mar-66778899',
    referencia_portal: 'OLX-66778899',
    aceita_corretores: 'SIM',
    data_publicacao: '2026-07-12',
    data_scraping: '2026-07-16T18:00:00Z',
    data_atualizacao: '2026-07-16T18:00:00Z',
    ativo: true,
  },
  {
    id: 'imovel-011',
    titulo: 'Estudio T0 para arrendamento junto a Universidade de Coimbra',
    descricao:
      'Estudio T0 mobilado e equipado, perfeito para estudantes. Kitchenette com placa, frigorifico e micro-ondas. Casa de banho com base de duche. Zona central de Coimbra, a 3 minutos a pe da Universidade. Despesas de agua e condominio incluidas na renda.',
    preco: 500,
    tipologia: 'T0',
    area_util: 28,
    area_bruta: 32,
    quartos: 0,
    casas_banho: 1,
    andar: '4.º',
    estado: 'usado',
    tipo: 'apartamento',
    finalidade: 'arrendamento',
    distrito: 'Coimbra',
    concelho: 'Coimbra',
    freguesia: 'Santo Antonio dos Olivais',
    morada: 'Rua Olimpio Nicolau Rui Fernandes 3',
    codigo_postal: '3000-303',
    latitude: 40.2116,
    longitude: -8.4207,
    garagem: false,
    elevador: true,
    varanda: false,
    terraço: false,
    jardim: false,
    piscina: false,
    ar_condicionado: false,
    certificado_energetico: 'E',
    fotos: [
      'https://picsum.photos/seed/imovel11a/800/600',
      'https://picsum.photos/seed/imovel11b/800/600',
    ],
    foto_principal: 'https://picsum.photos/seed/imovel11a/800/600',
    portal: 'idealista',
    url_original: 'https://www.idealista.pt/imovel/11002233/',
    referencia_portal: 'IDL-11002233',
    aceita_corretores: 'SIM',
    data_publicacao: '2026-07-14',
    data_scraping: '2026-07-17T12:00:00Z',
    data_atualizacao: '2026-07-17T12:00:00Z',
    ativo: true,
  },
  {
    id: 'imovel-012',
    titulo: 'Moradia T3 tradicional em Guimaraes',
    descricao:
      'Moradia T3 em pedra totalmente recuperada no centro historico de Guimaraes. 3 quartos, 2 casas de banho, sala com lareira, cozinha regional equipada. Quintal com 80 m². Detalhes originais preservados: cantaria em granito, tetos em madeira de castanho. Classificada como patrimonio local.',
    preco: 280000,
    tipologia: 'T3',
    area_util: 140,
    area_bruta: 165,
    area_terreno: 80,
    quartos: 3,
    casas_banho: 2,
    andar: 'R/C + 1.º',
    estado: 'renovado',
    tipo: 'moradia',
    finalidade: 'venda',
    distrito: 'Braga',
    concelho: 'Guimaraes',
    freguesia: 'Oliveira, Sao Paio e Sao Sebastiao',
    morada: 'Rua de Santa Maria 48',
    codigo_postal: '4800-443',
    latitude: 41.4431,
    longitude: -8.2918,
    garagem: false,
    elevador: false,
    varanda: false,
    terraço: false,
    jardim: true,
    piscina: false,
    ar_condicionado: false,
    certificado_energetico: 'C',
    fotos: [
      'https://picsum.photos/seed/imovel12a/800/600',
      'https://picsum.photos/seed/imovel12b/800/600',
      'https://picsum.photos/seed/imovel12c/800/600',
      'https://picsum.photos/seed/imovel12d/800/600',
    ],
    foto_principal: 'https://picsum.photos/seed/imovel12a/800/600',
    portal: 'imovirtual',
    url_original: 'https://www.imovirtual.com/anuncio/55443322',
    referencia_portal: 'IMV-55443322',
    aceita_corretores: 'NAO',
    restricao_texto: 'Particular, sem imobiliarias. Contacto direto com o proprietario apenas.',
    data_publicacao: '2026-06-25',
    data_scraping: '2026-07-13T14:00:00Z',
    data_atualizacao: '2026-07-13T14:00:00Z',
    ativo: true,
  },
];
